### ISSUE TITLE
Support for graceful restart (timeout)

### ISSUE THREAD

**Issue by basiliscos** [akarelas/ubic-service-hypnotoad#10]
Hello,

I have Mojolicious application with "heavy" webservices which execution time could be up to 10 minutes.

Hypnotoad supports graceful restart, i.e. the "heavy" requests aren't dropped. 

```Ubic::Service::Hypnotoad``` seems to be conforming that behaviour, but it reports to console ```broken```, while everything other seems to be working well. 

Thanks for good module!

**Comment by Logioniz** [comment]
I also have often `broken` status when stop hypnotoad on my small application.
May be need to increase timeout_options step/trials and value "5 seconds" or check infinity times status while pid exist in file.

**Comment by akarelas** [comment]
That's an interesting solution, @Logioniz . Being able to set step/trials in the config file. Would you like to implement it in a pull request?

**Comment by Logioniz** [comment]
Yes

**Comment by akarelas** [comment]
@basiliscos , your issue has been fixed in version 0.3 of the module!
